import {icon,esc} from './icons.js';
import {DOMAINS,LESSONS,QUESTIONS,lessonById} from '../data/curriculum.js';
import {prompt,pathState,serviceState,assessmentChecklist,expertInvestigation,FAULTS} from '../core/network.js';
import {shareSeed} from '../core/random.js';
import {formatTime} from '../core/clock.js';

export const button=(label,action,cls='secondary',extra='')=>`<button class="button ${cls}" data-action="${action}" ${extra}>${label}</button>`;
export const tag=(text,tone='')=>`<span class="tag ${tone}">${esc(text)}</span>`;
export function heading(eyebrow,title,detail='',right=''){return `<div class="page-heading"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1>${detail?`<p class="muted">${esc(detail)}</p>`:''}</div>${right}</div>`;}
export function empty(title,detail,action=''){return `<div class="empty">${icon('network')}<h2>${esc(title)}</h2><p>${esc(detail)}</p>${action}</div>`;}
export function shell(profile,ui,body){
  const routes=[['today','home','Today'],['study','book','Study'],['career','field','Career'],['sandbox','network','Sandbox'],['crew','crew','Crew'],['profile','user','Profile']];
  return `<div class="app-shell"><header class="topbar"><a class="brand" href="#today" aria-label="The Field, Today">${icon('terminal')}<span>THE FIELD<span class="brand-dot">.</span></span></a><div class="header-tools"><span class="connection"><span class="status-dot ${navigator.onLine?'':'amber'}"></span><span>${navigator.onLine?'Local workspace':'Offline'}</span></span><button class="icon-button" data-action="reference" aria-label="Open reference">${icon('book')}</button><button class="icon-button ${ui.menu?'active':''}" data-action="menu" aria-label="Open navigation" aria-expanded="${ui.menu}">${icon('menu')}</button></div></header>
  ${ui.menu?`<nav class="main-menu" aria-label="Main navigation">${routes.map(([route,symbol,title])=>`<a href="#${route}" class="${ui.route===route?'selected':''}">${icon(symbol)}${title}${icon('chevron')}</a>`).join('')}<span class="menu-version">Development build · 0.1.0</span></nav>`:''}
  ${ui.updateReady?`<div class="update-banner">An app update is downloaded. ${button('Save & update','update','small')}</div>`:''}
  <main id="main" class="main ${ui.route==='mission'?'mission-main':''}" tabindex="-1">${body}</main><footer class="app-footer"><span>${icon('terminal')}THE FIELD <b>0.1</b></span><span>${ui.saved?'Saved on this device':'Saving…'} <span class="status-dot"></span></span></footer></div>`;
}
export function today(profile,ui){
  const active=profile.activeMission,minutes=profile.plan?.minutes??20;
  const total=profile.activity.filter(a=>new Date(a.at).toDateString()===new Date().toDateString()).length;
  const next=LESSONS.find(l=>!profile.activity.some(a=>a.skill===l.id))??LESSONS[0];
  return `${heading('YOUR DAILY BRIEF',`Your next ${minutes} minutes.`,`Welcome back, ${profile.name}. Build one skill. Put it to work.`,button(`${icon('clock')} ${minutes} min ${icon('chevron')}`,'plan','secondary time-button'))}
  <div class="today-grid"><section class="panel plan-panel"><div class="section-heading"><h2>Today’s plan</h2>${tag(profile.goal==='career'?'Career focus':'CCNA focus','cyan')}</div>
  <div class="plan-line"><div class="step-number">01</div><div><span class="eyebrow">UNDERSTAND · 5 MIN</span><h3>${esc(next.title)}</h3><p class="muted">A short lesson, then a quick knowledge check.</p></div>${button(icon('arrow'),'lesson','icon-only',`data-id="${next.id}" aria-label="Study ${esc(next.title)}"`)}</div>
  <div class="plan-line"><div class="step-number">02</div><div><span class="eyebrow">APPLY · ${Math.max(5,minutes-5)} MIN</span><h3>${active?'Continue your investigation':'Investigate a customer outage'}</h3><p class="muted">${active?`${esc(active.ticket)} · ${esc(active.environment.name)}`:'Inspect the site, test your hypothesis, restore service.'}</p></div>${button(icon('arrow'),active?'resume-mission':'first-mission','icon-only','aria-label="Start field assignment"')}</div>
  <div class="plan-footer">${icon('target')} ${total?`${total} activities completed today`:'Your recommended path. Your pace.'}${button('Adjust plan','plan','text')}</div></section>
  <section class="panel signal-panel"><div class="section-heading"><h2>Your signal</h2>${icon('bolt')}</div><div class="xp-value">${profile.xp.toLocaleString()}<span>XP</span></div><p class="muted">${profile.history.filter(h=>h.type==='mission'&&h.passed).length} assignments resolved</p><div class="segmented-meter">${Array.from({length:16},(_,i)=>`<span class="${i<Math.min(16,Math.floor(profile.xp/50))?'lit':''}"></span>`).join('')}</div><div class="signal-caption"><span>Field technician</span><span>LEVEL ${1+Math.floor(profile.xp/500)}</span></div><a class="text-link" href="#profile">View your progress ${icon('arrow')}</a></section></div>
  <section class="dispatch-card"><div class="dispatch-content"><div class="eyebrow"><span class="status-dot amber"></span> NEXT ASSIGNMENT</div><h2>“Our internet<br>stopped working.”</h2><p>One customer. Several possible causes.<br>Follow the evidence from the cable to the CLI.</p><div class="inline-tags">${tag('Field visit')}${tag('15–20 min')}${tag('Guided')}</div>${button(`${active?'Resume investigation':'Accept assignment'} ${icon('arrow')}`,active?'resume-mission':'first-mission','primary')}</div><div class="dispatch-art" aria-hidden="true">${rackArt()}</div></section>
  <section><div class="section-heading spaced"><div><div class="eyebrow">CERTIFICATION PATH</div><h2>Six domains. One connected network.</h2></div><a class="text-link" href="#study">Open study ${icon('arrow')}</a></div><div class="domain-grid">${DOMAINS.map(d=>domainCard(d,profile)).join('')}</div></section>`;
}
function domainCard(d,p){const n=p.activity.filter(a=>a.domain===d.id).length;return `<button class="domain-card" data-action="domain" data-id="${d.id}"><span class="domain-number">${d.number}</span><span><h3>${d.name}</h3><small>${d.weight}% of blueprint · ${n?n+' practice activities':'Ready to explore'}</small></span>${icon('arrow')}</button>`;}
export function study(profile,ui){
  const domain=ui.domain??'all';const lessons=LESSONS.filter(l=>(domain==='all'||l.domain===domain)&&(!ui.query||`${l.title} ${l.lesson}`.toLowerCase().includes(ui.query.toLowerCase())));
  return `${heading('CERTIFICATION STUDY','Understand the network.','Read, recall, and apply. Switch study modes whenever you need.')}
  <div class="search-line"><label class="searchbox">${icon('search')}<input id="study-search" placeholder="Find a topic or command" value="${esc(ui.query??'')}" aria-label="Search study topics"></label>${button(`${icon('play')} Start practice`,'study-setup','primary')}</div>
  <div class="chips" aria-label="Filter domains">${[{id:'all',name:'All domains'},...DOMAINS].map(d=>`<button class="chip ${domain===d.id?'selected':''}" data-action="domain" data-id="${d.id}">${esc(d.name)}</button>`).join('')}</div>
  <div class="study-layout"><section class="panel topic-list"><div class="section-heading"><h2>${domain==='all'?'Learning path':DOMAINS.find(d=>d.id===domain)?.name}</h2><span class="muted">${lessons.length} topics</span></div>${lessons.map(l=>`<button class="topic-row" data-action="lesson" data-id="${l.id}"><span class="topic-index">${String(l.index+1).padStart(2,'0')}</span><span class="topic-copy"><strong>${esc(l.title)}</strong><small>${l.minutes} min · ${DOMAINS.find(d=>d.id===l.domain).name}</small></span>${profile.bookmarks.includes(l.id)?icon('flag'):icon('chevron')}</button>`).join('')||empty('No topics found','Try a broader search.')}</section><aside class="study-aside"><section class="panel"><div class="eyebrow">MAKE IT STICK</div><h2>A different way to recall.</h2><p class="muted">Switch between questions, flashcards, fill in the blank, and a word bank.</p>${['questions','flashcards','blank','wordbank'].map((m,i)=>button(`${icon(['target','copy','terminal','chip'][i])}${['Practice questions','Flashcards','Fill in the blank','Word bank'][i]}`,'study-mode','mode-button',`data-mode="${m}"`)).join('')}</section><section class="mentor-note">${icon('bulb')}<div><strong>A note from Mara</strong><p>“When a fact clicks, try breaking it in the lab. That’s when it starts to stick.”</p></div></section><p class="build-note">Starter content pack · 30 introductory topics. Full exam coverage and validated mastery banks are still in development.</p></aside></div>`;
}
export function lessonView(profile,id){const l=lessonById(id);return `${heading(DOMAINS.find(d=>d.id===l.domain).name,l.title,`${l.minutes} min · Foundation lesson`,button(`${icon('flag')} ${profile.bookmarks.includes(id)?'Saved':'Save'}`,'bookmark','secondary',`data-id="${id}"`))}<article class="panel lesson-article"><div class="eyebrow">THE IDEA</div><p class="lesson-lead">${esc(l.lesson)}</p><div class="example"><div class="eyebrow">ON THE JOB</div><p>${esc(l.example)}</p></div><div class="eyebrow">KEEP WITH YOU</div><code class="command-block">${esc(l.command)}</code><div class="lesson-actions">${button(`Practice this skill ${icon('arrow')}`,'skill-practice','primary',`data-id="${id}"`)}${button(`${icon('note')} Add a note`,'note','secondary',`data-id="${id}"`)}${button('Make a flashcard','make-card','text',`data-id="${id}"`)}</div></article>${button('Back to study','go-study','text')}`;}
export function studySession(profile,ui){
  const s=profile.session;if(!s)return empty('No study session','Choose a topic to begin.',button('Open study','go-study'));
  if(s.status==='complete')return studyReview(s);
  if(s.clock?.pausedAt!==null&&s.clock?.pausedAt!==undefined)return pausedView(s.clock,'resume-study');
  const q=s.items[s.index],mode=s.mode,locked=q.checked&&s.feedback==='immediate';
  const title=mode==='questions'?q.prompt:q.lesson.front;
  let answer='';
  if(mode==='questions')answer=`<div class="answers">${q.order.map((oi,i)=>`<button class="answer ${q.response===oi?'selected':''} ${locked&&oi===0?'correct':''} ${locked&&q.response===oi&&oi!==0?'incorrect':''}" data-action="answer" data-index="${oi}" ${locked?'disabled':''}><span class="answer-letter">${'ABCD'[i]}</span><span>${esc(q.options[oi])}</span>${locked&&oi===0?icon('check'):''}</button>`).join('')}</div>`;
  else if(mode==='flashcards'&&!ui.typedFlash)answer=`<div class="flashcard"><div class="eyebrow">${ui.flipped?'ANSWER':'RECALL FIRST'}</div><div>${ui.flipped?esc(q.lesson.answer):'Think it through. Then turn the card.'}</div>${button(ui.flipped?'Hide answer':'Reveal answer','flip','secondary')}</div>${ui.flipped?`<div class="row-buttons">${button('Still learning','self-check','secondary','data-value="false"')}${button(`${icon('check')} I knew it`,'self-check','primary','data-value="true"')}</div>`:''}${button('Switch to typed answers','typed-flash','text')}`;
  else if(mode==='wordbank')answer=`<div class="word-answer" aria-label="Constructed answer">${q.pieces.map(id=>`<button class="word-piece selected" data-action="unpick-word" data-id="${id}">${esc(q.bank.find(b=>b.id===id).text)}</button>`).join('')||'<span class="muted">Tap pieces to build your answer</span>'}</div><div class="word-bank">${q.bank.filter(b=>!q.pieces.includes(b.id)).map(b=>`<button class="word-piece" data-action="pick-word" data-id="${b.id}" ${locked?'disabled':''}>${esc(b.text)}</button>`).join('')}</div>`;
  else answer=`<form id="typed-answer"><label class="field-label" for="answer-text">Your answer</label><input id="answer-text" name="answer" class="large-input" placeholder="Type what you recall…" autocomplete="off" autocorrect="off" spellcheck="false" value="${esc(q.response??'')}" ${locked?'disabled':''}>${button('Check answer','check-answer','primary')}</form>`;
  return `${heading(s.assessment?'FRESH KNOWLEDGE CHECK':'STUDY SESSION',({questions:'Put your knowledge to work.',flashcards:'Make the connection.',blank:'Recall it yourself.',wordbank:'Build the answer.'})[mode],'',s.clock?`<span class="timer">${icon('clock')} <span id="clock">${formatTime(s.clock.remaining)}</span></span>`:button('Finish session','finish-study','secondary'))}
  <div class="session-layout"><section class="panel question-panel"><div class="question-meta"><span>QUESTION ${String(s.index+1).padStart(2,'0')} / ${s.items.length}</span>${button(`${icon('flag')} ${q.flag?'Flagged':'Flag for review'}`,'flag','text')}</div><div class="progress-track"><progress max="${s.items.length}" value="${s.index+1}" aria-label="Question progress"></progress></div><span class="tag cyan">${esc(q.lesson.title)}</span><h2 class="question-title">${esc(title)}</h2>${answer}
  ${locked?explanation(q,mode):''}
  <div class="question-footer">${button('Previous','question-prev','secondary',s.index===0?'disabled':'')}${mode==='questions'||mode==='wordbank'?button(locked?'Continue':'Check answer',locked?'question-next':'check-answer','primary',q.response===null&&!q.pieces.length?'disabled':''):''}${button(s.index===s.items.length-1?'Finish':'Next','question-next','text')}</div></section>
  <aside class="panel question-nav"><div class="eyebrow">YOUR SESSION</div><h3>${s.assessment?'90% passing target':s.feedback==='immediate'?'Immediate feedback':'Review at the end'}</h3><div class="question-dots">${s.items.map((item,i)=>`<button class="${i===s.index?'current':''} ${item.response!==null?'answered':''} ${item.flag?'flagged':''}" data-action="question-jump" data-index="${i}" aria-label="Question ${i+1}${item.flag?', flagged':''}">${i+1}</button>`).join('')}</div><p class="muted">${s.assessment?'Only unseen questions enter this check. It does not establish complete skill mastery in this starter pack.':'Your answers help identify what to revisit. There is no penalty for using reference material.'}</p>${s.clock?button('Pause assessment','pause-study','secondary'):button(`${icon('book')} Open reference`,'reference','secondary')}</aside></div>`;
}
function explanation(q,mode){return `<div class="feedback ${q.correct?'is-correct':'is-incorrect'}"><strong>${q.correct?'That’s right.':'Keep this distinction in mind.'}</strong><p>${esc(mode==='questions'?q.explanations[0]:q.lesson.answer)}</p>${mode==='questions'?q.options.map((o,i)=>`<details><summary>${i===0?'Correct answer':'Option'}: ${esc(o)}</summary><p>${esc(q.explanations[i])}</p></details>`).join(''):''}<details><summary>Scenario summary</summary><p>${esc(q.summary)}</p></details></div>`;}
function studyReview(s){const count=s.items.filter(i=>i.correct).length,score=Math.round(count/s.items.length*100);return `${heading('SESSION DEBRIEF',s.assessment?(score>=90?'Knowledge check passed.':'A few things to revisit.'):'Practice complete.',`${count} of ${s.items.length} correct · ${score}%`)}<div class="review-summary panel"><span class="review-score">${score}<small>%</small></span><div><h2>${s.assessment?'90% passing target':'One more step forward.'}</h2><p class="muted">${s.assessment?'Keep building evidence through varied practical work.':'Review the distinctions you missed, then apply a concept in a field assignment.'}</p>${button('Practice again','study-setup','primary')}${button('Open career','go-career','secondary')}</div></div><div class="review-list">${s.items.map((q,i)=>`<details class="panel"><summary><span class="${q.correct?'good':'bad'}">${icon(q.correct?'check':'close')}</span><span>${i+1}. ${esc(s.mode==='questions'?q.prompt:q.lesson.front)}</span></summary><p>Your answer: ${esc(s.mode==='questions'?(q.options[q.response]??'Unanswered'):(typeof q.response==='boolean'?q.response?'Self-checked: recalled':'Self-checked: still learning':q.response??'Unanswered'))}</p>${explanation(q,s.mode)}</details>`).join('')}</div>`;}
export function pausedView(clock,action){return `<div class="pause-screen">${icon('pause')}<div class="eyebrow">ASSESSMENT PAUSED</div><h1>Take a moment.</h1><p>Questions and the task are hidden.</p><p class="muted">Five minutes total interruption allowance.<br>Time already used: ${formatTime(clock.pauseUsed)}</p>${button('Resume assessment',action,'primary')}</div>`;}
export function career(profile,ui){const active=profile.activeMission;return `${heading('NORTHLINE FIBER · OPERATIONS','Your shift starts here.','Inspect the site. Follow the evidence. Leave the customer connected.',button(`${icon('copy')} Enter a seed`,'seed','secondary'))}<section class="career-intro panel"><div class="avatar small ${esc(profile.career.avatar.color)}">${icon('user')}</div><div><div class="eyebrow">CHAPTER 01</div><h2>Field technician</h2><p class="muted">${esc(profile.name)} · ${esc(profile.career.isp)}</p></div><span class="mentor-status"><span class="status-dot"></span> Mara is available</span></section>
  ${active?`<section class="resume-strip"><div>${tag(active.mode==='assessment'?'Practical assessment':'Active assignment','cyan')}<h3>${esc(active.ticket)} · ${esc(active.environment.name)}</h3></div>${button('Resume','resume-mission','primary')}</section>`:''}
  <div class="section-heading spaced"><h2>Assignment board</h2><span class="muted">Choose your difficulty</span></div><div class="ticket-grid">${[1,2,3].map((level,i)=>`<article class="panel ticket-card"><div class="section-heading">${tag(['RECOMMENDED','INVESTIGATE','MULTIPLE FAULTS'][i],['cyan','amber','violet'][i])}<span class="ticket-number">0${level}</span></div><div class="ticket-art">${icon(['wifi','network','chip'][i])}</div><h2>${['Customer offline','A more complicated visit','Trace the whole service'][i]}</h2><p>${['Start with one underlying fault and a mentor on request.','Investigate two faults in the same customer network.','Separate three interacting faults and verify the complete repair.'][i]}</p><div class="ticket-meta"><span>${icon('clock')} ${[15,20,30][i]} min</span><span>${icon('target')} Tier ${level}</span></div>${button(`Open assignment ${icon('arrow')}`,'mission-setup','secondary wide',`data-difficulty="${level}"`)}</article>`).join('')}</div><div class="mentor-note">${icon('bulb')}<div><strong>Mara · Senior technician</strong><p>“Start with what the customer can tell you. The first useful tool is usually a good question.”</p></div></div>`;}

export function missionView(profile,ui){const m=profile.activeMission;if(!m)return empty('No assignment open','Choose a ticket from your board.',button('Open career','go-career'));
  if(m.clock?.pausedAt!==null&&m.clock?.pausedAt!==undefined)return pausedView(m.clock,'resume-practical');
  if(m.status==='complete')return missionDebrief(m);
  const tabs=[['overview','field','Site'],['terminal','terminal','Terminal'],['evidence','search','Evidence'],['ticket','note','Ticket']];
  return `<div class="mission-header"><div><a class="text-link" href="#career">${icon('chevron','reverse')} Assignment board</a><div class="mission-title"><h1>${esc(m.environment.name)}</h1>${tag(m.mode==='guided'?'Guided practice':m.mode==='assessment'?'Assessment':'Career',m.mode==='assessment'?'amber':'cyan')}</div><p>${esc(m.ticket)} · ${esc(m.environment.type)} ${m.mode==='guided'?`· ${m.faults.length} underlying fault${m.faults.length>1?'s':''}`:''}</p></div><div class="mission-actions">${m.clock?`<span class="timer">${icon('clock')} <span id="clock">${formatTime(m.clock.remaining)}</span></span>`:''}${m.mode!=='assessment'?button(`${icon('bulb')} Hint`,'hint','secondary'):''}${button(icon('pause'),'leave-mission','icon-only','aria-label="Pause or leave mission"')}</div></div>
  ${m.failed?`<div class="failure-banner"><strong>Scored attempt ended.</strong> ${esc(m.failReason??'An additional required service was lost.')}<div>${button('Continue as recovery practice','recover','secondary')}${button('View debrief','failed-debrief','text')}</div></div>`:''}
  <div class="mission-tabs" role="tablist" aria-label="Mission views">${tabs.map(([id,symbol,label])=>`<button role="tab" aria-selected="${ui.missionTab===id}" class="${ui.missionTab===id?'selected':''}" data-action="mission-tab" data-id="${id}">${icon(symbol)}${label}${id==='evidence'?`<span class="tab-count">${m.evidence.length}</span>`:''}</button>`).join('')}</div>
  <div class="mission-workspace ${ui.missionTab==='terminal'?'terminal-workspace':''}">${ui.missionTab==='terminal'?terminalPanel(m,ui):ui.missionTab==='evidence'?evidencePanel(m):ui.missionTab==='ticket'?ticketPanel(m):sitePanel(m,ui)}</div>`;
}
function sitePanel(m,ui){return `<section class="panel site-panel"><div class="section-heading"><div><div class="eyebrow">CUSTOMER PREMISES</div><h2>Follow the physical path.</h2></div>${button('Service order','inspect','text','data-id="order"')}</div><div class="site-scene"><div class="scene-wall"><span class="wall-label">${esc(m.environment.name.toUpperCase())} / COMMS</span><div class="scene-window"><div></div></div><div class="scene-shelf"></div><button class="scene-ont" data-action="equipment" data-id="ont" aria-label="Inspect ONT"><span class="equipment-label">NORTHLINE / ONT</span><span class="equipment-lights"><i class="${m.physical.power?'green':''}"></i><i class="${m.physical.power&&m.physical.fiber?'green':''}"></i><i class="${m.physical.power&&m.physical.cable?'green':''}"></i></span><span class="scene-port"></span></button><button class="scene-router" data-action="equipment" data-id="router" aria-label="Inspect customer router"><i></i><i></i><span>GATEWAY</span><span class="router-led"></span></button><button class="scene-laptop" data-action="equipment" data-id="client" aria-label="Inspect workstation"><span class="laptop-display">${icon('terminal')}<b>WORKSTATION</b></span><span class="laptop-base"></span></button><div class="scene-wire"></div><div class="scene-floor"></div><span class="scene-caption">Tap equipment to inspect</span></div><div class="scene-hotspots">${button(`${icon('chip')} ONT`,'equipment','secondary','data-id="ont"')}${button(`${icon('wifi')} Router`,'equipment','secondary','data-id="router"')}${button(`${icon('terminal')} Workstation`,'equipment','secondary','data-id="client"')}</div></section><aside><section class="panel topology-panel"><div class="section-heading"><h2>Service topology</h2>${m.mode!=='assessment'?button('Follow traffic','traffic','text'):''}</div>${topology(m)}<p class="muted small-text">Select a device to open its workspace.</p></section><section class="panel contact-panel"><div class="eyebrow">CUSTOMER REPORT</div><h3>${esc(m.environment.person)}</h3><p>“The internet stopped working. I haven’t been able to get online.”</p>${button('Ask a question','conversation','secondary wide')}</section></aside>`;}
function terminalPanel(m,ui){const id=m.activeDevice;return `<section class="terminal-panel"><div class="terminal-toolbar"><label class="device-picker">${icon('terminal')}<select id="device-select" aria-label="Select device"><option value="access" ${id==='access'?'selected':''}>Access-SW</option><option value="edge" ${id==='edge'?'selected':''}>Edge-R1</option><option value="client" ${id==='client'?'selected':''}>${esc(m.environment.device)}</option></select></label><span class="terminal-session-label">${id==='client'?'LOCAL SHELL':'CONSOLE / SIMULATED IOS'}</span>${m.mode!=='assessment'?button(ui.builder?'Type commands':'Build commands','builder','text'):''}</div>
  <div class="terminal-output" id="terminal-output" role="log" aria-label="Terminal output"><div class="terminal-welcome">${id==='client'?`${esc(m.environment.device)} · customer workstation`:`${esc(m.devices[id].name)} · Console session opened`}<br>Type ${id==='client'?'help':'?'} for available commands.</div>${m.terminal[id].map(t=>`<div class="terminal-entry"><div><span class="terminal-prompt">${esc(t.prompt)}</span>${esc(t.input)}</div>${t.output?`<pre>${esc(t.output)}</pre>`:''}</div>`).join('')}</div>
  ${ui.builder&&m.mode!=='assessment'?`<div class="command-builder"><label>Choose a command <select id="builder-command">${(id==='client'?['ipconfig /all','ip addr','ping '+m.expected.gateway,'ping 198.51.100.10','nslookup status.northline.test','curl https://status.northline.test']:['enable','show interfaces status','show vlan brief','show running-config','show ip route','configure terminal','interface '+m.port,'switchport access vlan '+m.vlan,'no shutdown','end','copy running-config startup-config']).map(c=>`<option>${esc(c)}</option>`).join('')}</select></label>${button('Insert','insert-command','secondary')}</div>`:''}
  <form id="command-form" class="command-line"><span>${esc(prompt(m,id))}</span><input id="command-input" name="command" aria-label="Terminal command" autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false" enterkeyhint="send" value="${esc(ui.commandDraft??'')}"><button class="command-send" type="submit" aria-label="Execute command">${icon('arrow')}</button></form></section>
  <aside><section class="panel topology-panel"><div class="section-heading"><h2>Your network</h2>${button('Service order','inspect','text','data-id="order"')}</div>${topology(m)}</section><section class="panel"><div class="eyebrow">VERIFY THE OUTCOME</div><h3>Test from the customer.</h3><p class="muted">Use the workstation shell to test IP reachability, DNS, and HTTPS.</p>${button('Open workstation','device','secondary wide','data-id="client"')}${m.mode==='career'?button('Request a restricted change','escalate','text'):''}</section></aside>`;}
function evidencePanel(m){return `<section class="panel evidence-panel"><div class="section-heading"><div><div class="eyebrow">AUTOMATICALLY CAPTURED</div><h2>What the network told you.</h2></div><span class="muted">${m.evidence.length} findings</span></div>${m.evidence.length?m.evidence.slice().reverse().map(e=>`<article class="finding"><div class="section-heading"><h3>${esc(e.title)}</h3>${tag(`State ${e.revision}`,e.revision===m.revision?'cyan':'')}</div><pre>${esc(e.detail)}</pre><label class="check-label"><input type="checkbox" data-evidence="${e.id}" ${m.docs.evidence.includes(e.id)?'checked':''}> Use in my conclusion</label></article>`).join(''):empty('No findings yet','Inspect equipment, run a command, or test the service. Findings will appear here automatically.')}</section>`;}
function ticketPanel(m){return `<div class="ticket-layout"><section class="panel"><div class="eyebrow">${esc(m.ticket)}</div><h2>Restore and verify customer internet.</h2><p>Identify the underlying issue, restore the approved service, and preserve service to the other customer. Save device configuration changes before closing the ticket.</p><div class="requirements"><h3>Required outcomes</h3><ul><li>IP, DNS, and HTTPS tests succeed after the last change.</li><li>The customer confirms service is restored.</li><li>Cause, changes, and verification are documented with selected evidence.</li></ul>${m.mode==='assessment'?'<p class="amber-text">Any additional outage fails this attempt. No maintenance interruption is authorized.</p>':''}</div><div class="test-buttons">${['internet','dns','web'].map(t=>button(`${icon(m.verification[t]?.ok?'check':'play')} ${t==='internet'?'IP test':t==='dns'?'DNS query':'HTTPS test'}`,'test','secondary',`data-id="${t}"`)).join('')}${button('Ask customer to confirm','test','secondary','data-id="confirm"')}</div></section><section class="panel"><div class="eyebrow">YOUR HANDOFF</div><h2>Leave a useful record.</h2><form id="ticket-docs"><label>Underlying cause<textarea name="cause" placeholder="What failed, and why?" required>${esc(m.docs.cause)}</textarea></label><label>Action taken<textarea name="action" placeholder="What did you change? Include the device or connection." required>${esc(m.docs.action)}</textarea></label><label>Verification & customer impact<textarea name="verify" placeholder="What did you test after your final change?" required>${esc(m.docs.verify)}</textarea></label><p class="muted">${m.docs.evidence.length} findings selected. Choose supporting findings in Evidence.</p><div class="row-buttons">${button('Save notes','save-ticket','secondary')}${button(`Complete assignment ${icon('check')}`,'complete-mission','primary')}</div></form></section></div>`;}
export function topology(m){return `<div class="topology">${[['edge','Edge-R1','Upstream router'],['access','Access-SW','Service distribution'],['ont','ONT','Optical handoff'],['router','Customer router','LAN gateway'],['client',m.environment.device,'Customer workstation']].map(([id,name,role],i)=>`<button class="topology-node ${m.activeDevice===id?'selected':''}" data-action="${['access','edge','client'].includes(id)?'device':'equipment'}" data-id="${id}"><span class="topology-symbol">${icon(['network','chip','chip','wifi','terminal'][i])}</span><span><strong>${esc(name)}</strong><small>${role}</small></span><span class="node-index">0${i+1}</span></button>`).join('')}</div>`;}
export function missionDebrief(m){const check=assessmentChecklist(m);return `${heading('ASSIGNMENT DEBRIEF',m.failed?'A recovery opportunity.':'Service restored.',`${m.ticket} · ${m.environment.name}`)}<section class="panel completion-panel"><div class="completion-icon">${icon(m.failed?'bulb':'check')}</div><div><div class="eyebrow">${m.failed?'SCORED ATTEMPT ENDED':'CUSTOMER BACK ONLINE'}</div><h2>${m.failed?'Review what happened.':`+${m.credit?.total??0} XP`}</h2><p>${m.failed?'Recover in practice, then try a fresh variant.':'You investigated, made a change, and verified the result.'}</p></div>${button('Back to the board','go-career','primary')}</section>${m.credit?`<details class="panel credit-details"><summary>How your career credit was calculated</summary><p>Base: ${m.credit.base} XP · Assistance: ${Math.round(m.credit.deduction*100)}% · Repeat multiplier: ${m.credit.multiplier*100}%</p><p class="muted">Reference ${(m.credit.deductions.reference*100).toFixed(0)}% · Command building ${(m.credit.deductions.builder*100).toFixed(1)}% · Guidance ${(m.credit.deductions.guidance*100).toFixed(0)}%. Total assistance is capped at 50%. Guided practice has no assistance deduction.</p></details>`:''}<div class="debrief-grid"><section class="panel"><h2>Outcome review</h2>${check.map(c=>`<div class="check-row ${c.ok?'good':'bad'}">${icon(c.ok?'check':'close')}<span>${c.label}</span></div>`).join('')}<h3>Underlying problems</h3>${m.faults.map(f=>`<p>${esc(FAULTS[f].label)}</p>`).join('')}</section><section class="panel"><h2>An expert investigation</h2><ol class="expert-steps">${expertInvestigation(m).map(t=>`<li>${esc(t)}</li>`).join('')}</ol><p class="muted">This is one valid approach. Other investigations can meet the same outcomes.</p></section></div><details class="panel"><summary>Your action replay (${m.events.length} events)</summary><ol class="event-list">${m.events.map(e=>`<li><span class="eyebrow">${esc(e.type)} · STATE ${e.revision}</span><p>${esc(e.text)}</p>${e.output?`<pre>${esc(e.output)}</pre>`:''}</li>`).join('')}</ol></details><div class="row-buttons">${button('Replay exact seed','replay','secondary')}${button('Generate a variation','variation','primary')}${button('Copy seed','copy-seed','text')}</div>`;}
export function profileView(p){const answered=p.activity.filter(a=>a.type==='study'),correct=answered.reduce((n,a)=>n+a.correct,0),total=answered.reduce((n,a)=>n+a.total,0);return `${heading('YOUR PROGRESS','Evidence of your progress.','Knowledge practice and field experience, in one place.',button(`${icon('settings')} Settings`,'settings','secondary'))}<div class="profile-grid"><section class="panel"><div class="avatar ${esc(p.career.avatar.color)}">${icon('user')}</div><h2>${esc(p.name)}</h2><p class="muted">Field technician · Level ${1+Math.floor(p.xp/500)}</p>${button('Customize technician','avatar','secondary')}<div class="metric-row"><span>Experience</span><strong>${p.xp} XP</strong></div><div class="metric-row"><span>Knowledge practice</span><strong>${total?Math.round(correct/total*100)+'%':'—'}</strong></div><div class="metric-row"><span>Assignments resolved</span><strong>${p.history.filter(h=>h.type==='mission'&&h.passed).length}</strong></div><p class="muted small-text">Practice accuracy is not a certification-readiness score.</p></section><section class="panel"><h2>Skill evidence</h2>${DOMAINS.map(d=>`<div class="skill-evidence"><div><strong>${d.name}</strong><small>${p.activity.filter(a=>a.domain===d.id).length} recorded study activities</small></div>${icon('book')}</div>`).join('')}<p class="muted">Full mastery requires fresh knowledge assessments and varied independent practical demonstrations. This development build records practice evidence.</p></section></div><div class="section-heading spaced"><h2>Your saved workspace</h2>${button('Export local progress','export','secondary')}</div><div class="debrief-grid"><section class="panel"><h3>Bookmarks</h3>${p.bookmarks.length?p.bookmarks.map(id=>{const l=lessonById(id);return l?`<button class="topic-row" data-action="lesson" data-id="${id}">${icon('flag')}<span>${esc(l.title)}</span>${icon('chevron')}</button>`:'';}).join(''):'<p class="muted">Save a lesson to keep it close.</p>'}<h3>Personal notes</h3>${p.notes.map(n=>`<details><summary>${esc(lessonById(n.topic)?.title??n.topic)}</summary><p>${esc(n.text)}</p></details>`).join('')||'<p class="muted">Attach a note to a lesson as you study.</p>'}</section><section class="panel"><h3>Personal flashcards</h3>${p.cards.map(c=>`<details><summary>${esc(c.front)}</summary><p>${esc(c.back)}</p>${button('Edit card','edit-card','text',`data-id="${c.id}"`)}</details>`).join('')||'<p class="muted">Create a card from a saved concept or write your own.</p>'}${button('Create a card','new-card','secondary')}</section></div>`;}
export function crewView(){return `${heading('CREW WORKSPACE','Better, together.','Cooperate on tickets and compare challenge results.')}<section class="panel">${empty('Crew services are not connected yet.','This development build runs on your device. Invitations, live device handoffs, shared networks, and competitive results need the authenticated synchronization service. They are not simulated as real group activity.')}<div class="crew-capabilities"><div>${icon('crew')}<h3>2–4 technicians</h3><p>Individual roles on a shared assignment.</p></div><div>${icon('shield')}<h3>Controlled handoffs</h3><p>One configuration controller per device.</p></div><div>${icon('target')}<h3>Shared challenges</h3><p>Identical seeds, comparable outcomes.</p></div></div></section>`;}
export function sandboxView(){return `${heading('PERSONAL LAB','Explore a working network.','Try configurations, make mistakes, and inspect what changes.')}<section class="panel sandbox-start"><div>${icon('network')}<h2>Customer access lab</h2><p>Open a clean version of the service network. Configure the switch and edge router, change workstation settings, or disconnect equipment. No career credit or assessment penalties.</p>${button(`Open lab ${icon('arrow')}`,'new-sandbox','primary')}</div>${rackArt()}</section><p class="build-note">The blank-canvas topology editor and arbitrary device linking are scheduled for the next simulator stage.</p>`;}
export function rackArt(){return `<svg viewBox="0 0 480 340" class="rack-art" fill="none" aria-hidden="true"><defs><linearGradient id="rack-glow" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#173144"/><stop offset="1" stop-color="#0c1823"/></linearGradient></defs><path d="M12 263h73v-57h40M348 153h57v-64h60M48 91h77" stroke="#1d4254"/><circle cx="48" cy="91" r="5" fill="#51c9dd"/><circle cx="466" cy="89" r="5" fill="#51c9dd"/><path d="m134 77 168-27 64 38v196l-168 30-64-37z" fill="#0a121b" stroke="#325366"/><path d="m134 77 64 39 168-28m-168 28v198" stroke="#325366"/><path d="m144 94 40 24v28l-40-24zm0 48 40 24v28l-40-24zm0 48 40 24v28l-40-24" fill="#142330"/><path d="m208 127 146-25v43l-146 26zm0 59 146-25v43l-146 26zm0 59 146-25v43l-146 26z" fill="url(#rack-glow)" stroke="#294553"/>${[0,1,2].map(row=>Array.from({length:8},(_,i)=>`<path d="m${220+i*15} ${140+row*59-i*2.55} 9-1.6v10l-9 1.6z" fill="${i===6?'#3e8b8f':'#061018'}" stroke="#31505e"/>`).join('')).join('')}<path d="M245 210v45c0 40-51 43-51 7v-14M283 144v83c0 39 39 31 39 1v-12" stroke="#48afbc" stroke-width="3"/><path d="M233 151v64c0 25-43 19-43-4v-49" stroke="#3d6680" stroke-width="3"/><text x="243" y="81" fill="#528496" font-size="9" font-family="monospace" transform="rotate(-10 243 81)">NORTHLINE / ACCESS</text></svg>`;}
