import {openStore,readState,writeState,newProfile,validateBackup} from './core/store.js';
import {createMission,execute,prompt,setPhysical,setClient,inspect,runTest,getHint,serviceState,pathState,assessmentChecklist,evidence,FAULTS} from './core/network.js';
import {newStudy,checkItem,finishStudy,PREREQUISITE_TASKS} from './core/study.js';
import {newClock,tick,pauseClock,resumeClock,formatTime} from './core/clock.js';
import {careerCredit,prerequisiteScore} from './core/scoring.js';
import {freshSeed,rng,shuffle,challengeKey,shareSeed,parseSeed,GENERATOR_VERSION} from './core/random.js';
import {redeemAuthorization} from './core/authorization.js';
import {DOMAINS,LESSONS,QUESTIONS,lessonById} from './data/curriculum.js';
import {icon,esc} from './ui/icons.js';
import * as views from './ui/views.js';

const root=document.querySelector('#app'),modal=document.querySelector('#modal');
const ui={phase:'intro',route:'today',menu:false,saved:true,missionTab:'overview',domain:'all',query:'',builder:false,commandDraft:'',assistedDraft:false,flipped:false,typedFlash:false,updateReady:false,bootText:'',bootError:'',codeMode:false};
let profile=null,deployment={},registration=null,saveQueue=Promise.resolve(),toastTimer,gate=null,ready=false;
let writeLock=null,lockResolve=null;
const {button,heading,tag,empty}=views;
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4000);}
function save(){if(!profile)return Promise.resolve();ui.saved=false;const copy=structuredClone(profile);saveQueue=saveQueue.catch(()=>{}).then(()=>writeState(copy)).then(()=>{ui.saved=true;}).catch(error=>{ui.saved=false;toast('Could not save on this device. Export your work before closing the app.');console.error(error);});return saveQueue;}
function closeModal(){modal.close();modal.innerHTML='';}
function showModal(title,content,wide=false){modal.className=wide?'wide-modal':'';modal.innerHTML=`<div class="modal-heading"><h2>${esc(title)}</h2><button class="icon-button" data-action="close-modal" aria-label="Close dialog">${icon('close')}</button></div><div class="modal-body">${content}</div>`;if(!modal.open)modal.showModal();}
function go(route){
  if(ui.route==='mission'&&route!=='mission'){syncDocs();const c=profile?.activeMission?.clock;if(c&&!c.ended)pauseClock(c);save();}
  if(ui.route==='session'&&route!=='session'){const c=profile?.session?.clock;if(c&&!c.ended)pauseClock(c);save();}
  ui.route=route;ui.menu=false;location.hash=route;render();window.scrollTo({top:0});
}
function appearance(){document.documentElement.dataset.theme=profile?.settings.theme??'cyan';document.documentElement.dataset.text=profile?.settings.textSize??'normal';document.documentElement.dataset.density=profile?.settings.comfortable?'comfortable':'compact';}
function render(){
  appearance();
  if(ui.phase==='intro')return intro();
  if(ui.phase==='loading')return;
  if(ui.phase==='locked'){root.innerHTML='<div class="locked-screen"><p>you are not ready</p></div>';return;}
  if(ui.phase==='onboard')return onboarding();
  if(ui.phase==='gate')return gateView();
  const renderers={today:()=>views.today(profile,ui),study:()=>views.study(profile,ui),lesson:()=>views.lessonView(profile,ui.lesson??LESSONS[0].id),session:()=>views.studySession(profile,ui),career:()=>views.career(profile,ui),mission:()=>views.missionView(profile,ui),profile:()=>views.profileView(profile),crew:views.crewView,sandbox:views.sandboxView};
  root.innerHTML=views.shell(profile,ui,(renderers[ui.route]??renderers.today)());
  if(ui.route==='mission'&&ui.missionTab==='terminal'){const out=document.querySelector('#terminal-output');if(out)out.scrollTop=out.scrollHeight;}
}
function intro(){root.innerHTML=`<div class="boot-screen"><form id="boot-form" autocomplete="off">${ui.codeMode?'<p>you don’t have permission</p><p>enter code</p>':''}<div class="boot-line"><span id="boot-display">${esc(ui.bootText)}</span><span class="block-cursor" aria-hidden="true"></span><input id="boot-input" aria-label="${ui.codeMode?'Enter your reassessment authorization code':'Type enable, then press Enter'}" value="${esc(ui.bootText)}" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false" enterkeyhint="go"></div>${ui.bootError?`<p class="boot-error">${esc(ui.bootError)}</p>`:''}</form></div>`;document.querySelector('#boot-input')?.focus({preventScroll:true});}
async function enterApp(){ui.phase='loading';root.innerHTML='<div class="boot-screen"><pre id="init-log" aria-live="polite"></pre></div>';const lines=['> THE FIELD / INITIALIZING','[ok] Local workspace opened','[ok] Simulation engine ready','[ok] Content pack loaded'];const el=document.querySelector('#init-log');for(const line of lines){el.textContent+=line+'\n';await new Promise(r=>setTimeout(r,95));}if(!profile){ui.phase='onboard';render();return;}if(profile.gate!=='passed'){ui.phase='gate';gate=profile.gateAttempt??null;render();return;}ui.phase='ready';ui.route=['today','study','career','mission','profile','crew','sandbox','session'].includes(location.hash.slice(1))?location.hash.slice(1):'today';render();}
function onboarding(){root.innerHTML=`<div class="onboarding"><a class="brand">${icon('terminal')} THE FIELD<span class="brand-dot">.</span></a><div class="onboarding-body"><div class="eyebrow">FIRST CONNECTION</div><h1>Your fieldwork<br>starts here.</h1><p class="muted">Networking study and realistic practice, on your device.</p><form id="onboard-form"><label>Your name<input name="name" maxlength="50" required autocomplete="given-name" placeholder="Technician name"></label><label>Your first goal<select name="goal"><option value="ccna">Prepare for the CCNA</option><option value="career">Build practical job skills</option></select></label><div class="callout"><strong>Start with the prerequisite check</strong><p>A brief knowledge and practical check confirms you’re ready for CCNA study. You need 70% overall. A completed failure locks access until the owner authorizes another attempt.</p></div><div class="build-note"><strong>Development build</strong> · Your profile stays on this device. Email sign-in, account recovery, and crew synchronization are not connected yet. This build is for owner review before group testing.</div><button class="button primary wide" type="submit">Create local profile ${icon('arrow')}</button></form></div><p class="onboarding-foot">Built for the work behind the knowledge.</p></div>`;}
function beginGate(){const seed=freshSeed(),r=rng(seed),knowledge=shuffle(r,QUESTIONS.filter(q=>['cabling','interfaces','ipv4','subnetting','troubleshooting'].includes(q.skill))).slice(0,5).map(q=>({...q,kind:'knowledge',response:null,order:shuffle(r,[0,1,2,3])}));const practical=PREREQUISITE_TASKS.map((t,i)=>{const network=createMission(seed+'-'+i,1,'gate',[i===2?'shutdown':i===4?'power':'dns']);return {kind:'practical',task:t.id,network,correct:null};});gate={items:[...knowledge,...practical],index:0,clock:newClock(1200),status:'active',seed};profile.gateAttempt=gate;save();render();}
function gateView(){
  if(!gate){root.innerHTML=`<div class="onboarding"><div class="onboarding-body">${heading('PREREQUISITE CLEARANCE',profile.gate==='authorized'?'Your reassessment is available.':'Confirm your starting point.','About 20 minutes · Knowledge and practical tasks')}<div class="panel"><p>Score at least 70% overall. Knowledge and practical work each contribute 50%. You’ll see only pass or fail when the check ends.</p><p>A five-minute total interruption allowance pauses the timer. A longer interruption lets you start a fresh check without a new authorization.</p><p class="small-text muted">Your local learner ID: <code class="breakable">${esc(profile.id)}</code><br>Keep this ID for the owner’s reassessment authorization.</p>${button('Start prerequisite check','begin-gate','primary wide')}</div></div></div>`;return;}
  if(gate.clock.pausedAt!==null){root.innerHTML=views.pausedView(gate.clock,'resume-gate');return;}
  const item=gate.items[gate.index];let task;
  if(item.kind==='knowledge')task=`<h2 class="question-title">${esc(item.prompt)}</h2><div class="answers">${item.order.map((oi,i)=>`<button class="answer ${item.response===oi?'selected':''}" data-action="gate-answer" data-index="${oi}"><span class="answer-letter">${'ABCD'[i]}</span><span>${esc(item.options[oi])}</span></button>`).join('')}</div>`;
  else{const t=PREREQUISITE_TASKS.find(t=>t.id===item.task),m=item.network;task=`<h2>${esc(t.title)}</h2><p class="muted">Assigned customer port: <code>${m.port}</code></p>${t.device==='physical'?`<div class="gate-equipment">${icon('chip')}<p>ONT power indicator: ${m.physical.power?'green':'off'}</p>${button('Inspect ONT','gate-inspect','secondary')}${button('Connect power supply','gate-power','secondary')}</div>`:`<div class="terminal-panel gate-terminal"><div class="terminal-output">${m.terminal[t.device].map(e=>`<div>${esc(e.prompt+e.input)}<pre>${esc(e.output)}</pre></div>`).join('')}</div><form id="gate-command" class="command-line"><span>${esc(prompt(m,t.device))}</span><input id="gate-input" name="command" aria-label="Prerequisite terminal command" autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false"><button type="submit" class="command-send" aria-label="Execute command">${icon('arrow')}</button></form></div>`}`;}
  root.innerHTML=`<div class="gate-container"><div class="section-heading"><div class="eyebrow">PREREQUISITE CHECK · ${gate.index+1} / 10</div><span class="timer">${icon('clock')}<span id="clock">${formatTime(gate.clock.remaining)}</span></span></div><section class="panel question-panel">${tag(item.kind==='knowledge'?'Knowledge':'Practical task','cyan')}${task}<div class="question-footer">${button('Previous','gate-prev','secondary',gate.index===0?'disabled':'')}${button('Pause','pause-gate','text')}${button(gate.index===9?'Submit check':'Next','gate-next','primary')}</div></section></div>`;
}
async function finishGate(interrupted=false){if(interrupted){profile.gateAttempt=null;gate=null;await save();showModal('Check interrupted','<p>Your pause allowance ended. You can start a fresh prerequisite check without an authorization code.</p>'+button('Continue','close-modal','primary'));render();return;}const items=gate.items.map(i=>({kind:i.kind,correct:i.kind==='knowledge'?i.response===0:PREREQUISITE_TASKS.find(t=>t.id===i.task).pass(i.network)}));const result=prerequisiteScore(items);profile.gate=result.passed?'passed':'locked';profile.gateAttempt=null;profile.grant=null;gate=null;await save();ui.phase=result.passed?'ready':'locked';render();if(result.passed)toast('Prerequisite check passed. Your workspace is unlocked.');}

function setupStudy(mode=ui.studyMode??'questions',skill=null){ui.studyMode=mode;showModal('Set up your practice',`<form id="study-setup-form"><label>Study mode<select name="mode">${[['questions','Practice questions'],['flashcards','Flashcards'],['blank','Fill in the blank'],['wordbank','Word bank']].map(([v,t])=>`<option value="${v}" ${v===mode?'selected':''}>${t}</option>`).join('')}</select></label><label>Domain<select name="domain">${[{id:'all',name:'All domains'},...DOMAINS].map(d=>`<option value="${d.id}" ${d.id===ui.domain?'selected':''}>${d.name}</option>`).join('')}</select></label>${skill?`<input name="skill" type="hidden" value="${esc(skill)}"><p>Topic: ${esc(lessonById(skill).title)}</p>`:''}<div class="form-columns"><label>Questions<select name="count"><option>5</option><option selected>10</option><option>20</option></select></label><label>Feedback<select name="feedback"><option value="immediate">After each answer</option><option value="end">At the end</option></select></label></div><label class="check-label"><input type="checkbox" name="assessment"> Fresh timed knowledge check (questions only, 90% target)</label><p class="muted small-text">An assessment needs enough unseen items. This starter pack does not yet establish complete skill mastery.</p><button class="button primary wide" type="submit">Start session ${icon('arrow')}</button></form>`);}
function markExposure(q){if(q&&!profile.exposures.includes(q.id))profile.exposures.push(q.id);}
async function completeStudy(reason=null){const s=profile.session;if(!s||s.status==='complete')return;finishStudy(s);if(s.clock){s.clock.ended=true;s.clock.reason=reason??'submitted';}const correct=s.items.filter(i=>i.correct).length;profile.activity.push({id:s.id,at:Date.now(),type:'study',domain:s.domain,skill:s.skill,correct,total:s.items.length});profile.history.push({id:s.id,type:'study',at:Date.now(),correct,total:s.items.length,assessment:s.assessment,reason,session:structuredClone(s)});for(const q of s.items)markExposure(q);if(!s.assessment)profile.xp+=correct*5;await save();render();}
function syncDocs(){const form=document.querySelector('#ticket-docs');if(form&&profile.activeMission)for(const key of ['cause','action','verify'])profile.activeMission.docs[key]=form.elements[key].value;}
function startMission(difficulty=1,mode='guided',seed=freshSeed(),sandbox=false){
  if(profile.activeMission?.status==='active'&&!ui.replaceApproved){showModal('Keep your current assignment?',`<p>Save a recovery copy of the current assignment before opening another. Applied changes and evidence will be kept in local history.</p>${button('Keep working','close-modal','secondary')}${button('Save a copy & continue','replace-mission','primary',`data-difficulty="${difficulty}" data-mode="${mode}" data-seed="${esc(seed)}" data-sandbox="${sandbox}"`)}`);return;}
  const m=createMission(seed,difficulty,mode);if(sandbox){m.sandbox=true;m.faults=[];m.physical={power:true,cable:true,fiber:true};m.client={...m.expected,platform:m.client.platform};m.devices.access.interfaces[m.port].vlan=m.vlan;m.devices.access.interfaces[m.port].admin=true;m.devices.edge.defaultRoute='203.0.113.1';for(const d of Object.values(m.devices)){d.saved=JSON.stringify({interfaces:d.interfaces,defaultRoute:d.defaultRoute});d.dirty=false;}}
  if(mode==='assessment')m.clock=newClock(difficulty*600+300);
  profile.activeMission=m;ui.replaceApproved=false;ui.builder=false;ui.assistedDraft=false;ui.commandDraft='';ui.missionTab='overview';save();closeModal();go('mission');
}
function missionSetup(difficulty){showModal('Choose the assignment format',`<div class="choice-list">${button(`<strong>Guided practice</strong><span>Fault count shown. Full configuration access. Free help.</span>`,'start-mission','choice-button',`data-mode="guided" data-difficulty="${difficulty}"`)}${button(`<strong>Career assignment</strong><span>Hidden faults. Restricted edge changes through your coworker.</span>`,'start-mission','choice-button',`data-mode="career" data-difficulty="${difficulty}"`)}${button(`<strong>Independent practical check</strong><span>Typed CLI and normal CLI help only. ${difficulty*10+5} minutes. Any additional outage fails the attempt.</span>`,'start-mission','choice-button',`data-mode="assessment" data-difficulty="${difficulty}"`)}</div><p class="muted small-text">All formats require verification and documentation. Practical checks record evidence; the complete skill-mastery system is still in development.</p>`);}
function equipment(id){const m=profile.activeMission;if(id==='client'){showModal('Workstation network settings',`<form id="client-settings"><p>${esc(m.environment.device)} · Ethernet adapter</p>${['ip','mask','gateway','dns'].map((key,i)=>`<label>${['IPv4 address','Subnet mask','Default gateway','DNS server'][i]}<input name="${key}" value="${esc(m.client[key])}" inputmode="decimal" autocomplete="off"></label>`).join('')}<div class="row-buttons"><button class="button primary" type="submit">Apply settings</button>${button('Open terminal','device','secondary','data-id="client"')}</div></form>`);inspect(m,'client');}
  else if(id==='router'){showModal('Customer router · RG-120',`<div class="equipment-closeup"><div class="equipment-name">NORTHLINE <small>RG-120</small></div><div class="port-row"><span class="physical-port blue-port">WAN</span>${[1,2,3,4].map(i=>`<span class="physical-port">LAN ${i}</span>`).join('')}</div></div><p>LAN gateway: <code>${m.expected.gateway}</code></p><p>WAN Ethernet link: <strong>${m.physical.power&&m.physical.cable?'up':'down'}</strong></p>${button('Test HTTPS service','test','primary','data-id="web"')}`);}
  else{const result=inspect(m,'ont');showModal('Optical network terminal · ONT-240',`<div class="equipment-closeup"><div class="equipment-name">NORTHLINE <small>ONT-240</small></div><div class="led-row">${[['POWER',m.physical.power],['PON',m.physical.power&&m.physical.fiber],['LAN',m.physical.power&&m.physical.cable]].map(([label,on])=>`<span><i class="${on?'green':''}"></i>${label}</span>`).join('')}<span><i class="${m.physical.power&&!m.physical.fiber?'red':''}"></i>LOS</span></div><div class="port-row"><span class="physical-port fiber-port">PON</span><span class="physical-port blue-port">GE1</span><span class="power-jack">12V DC</span></div></div><pre>${esc(result)}</pre><div class="row-buttons">${button(m.physical.power?'Disconnect power':'Connect power supply','physical','secondary',`data-key="power" data-value="${!m.physical.power}"`)}${button('Connect Ethernet cable','cable','secondary')}${m.physical.cable?button('Disconnect Ethernet','physical','text','data-key="cable" data-value="false"'):''}${button('Read optical meter','inspect','text','data-id="optical"')}</div>`);}save();}
function cableStep(step=0){showModal('Connect the Ethernet link',`<div class="eyebrow">${step+1} / 3</div><h3>${['Choose the cable.','Choose its source port.','Choose its destination port.'][step]}</h3><div class="choice-list">${step===0?button('Cat6 Ethernet patch cable','cable-step','choice-button','data-step="1"'):step===1?button('ONT · GE1','cable-step','choice-button','data-step="2"'):button('Customer router · WAN','connect-cable','choice-button')}</div>`);}
function conversation(){const m=profile.activeMission;showModal(`${m.environment.person} · Customer`,`${m.conversations.map(c=>`<div class="dialogue"><span class="eyebrow">${esc(c.speaker)}</span><p>${esc(c.text)}</p></div>`).join('')}<div class="suggested-questions">${['When did this start?','Is every device affected?','Has anything changed?','What do the equipment lights show?'].map((q,i)=>button(q,'ask-customer','secondary',`data-index="${i}"`)).join('')}</div><form id="customer-question" class="inline-form"><input name="question" aria-label="Type a customer question" placeholder="Or ask in your own words…" maxlength="300" required><button class="button primary" type="submit">Ask</button></form>`);}
function answerCustomer(question){const m=profile.activeMission;let answer;
  if(/when|start|long/i.test(question))answer='It was working earlier today. I noticed the problem when I tried to open our usual websites.';
  else if(/every|all|device|phone|scope/i.test(question))answer='The workstation and the other connected devices all have trouble reaching websites.';
  else if(/chang|mov|touch|power|cable/i.test(question))answer=m.faults.some(f=>['power','cable'].includes(f))?'We moved some equipment to clean the shelf. I’m not sure whether anything came loose.':'I haven’t changed anything myself. I don’t know whether there was any network work.';
  else if(/light|indicator/i.test(question))answer=inspect(m,'ont');
  else if(/work|load|fix|connect|now/i.test(question))answer=runTest(m,'confirm').detail;
  else answer='I’m not sure how to answer that. Could you ask about when it started, which devices are affected, recent changes, or the equipment indicators?';
  m.conversations.push({speaker:'You',text:question},{speaker:m.environment.person,text:answer});evidence(m,'Customer statement',question+'\n'+answer,'conversation');save();conversation();}
function reference(){const m=profile.activeMission;if(ui.route==='mission'&&m?.mode==='assessment'){toast('Only normal CLI help is available during this assessment.');return;}if(profile.session?.assessment&&profile.session.status==='active'&&ui.route==='session'){toast('Reference is unavailable during this knowledge check.');return;}if(ui.route==='mission'&&m?.status==='active'){m.help.referenceOpens++;save();}showModal('Field reference',`<label class="searchbox">${icon('search')}<input id="reference-search" placeholder="Find a command or concept" aria-label="Search reference"></label><div id="reference-results">${referenceItems('')}</div>`,true);}
function referenceItems(query){return LESSONS.filter(l=>`${l.title} ${l.command} ${l.front}`.toLowerCase().includes(query.toLowerCase())).map(l=>`<details class="reference-entry"><summary>${esc(l.title)}<code>${esc(l.command)}</code></summary><p>${esc(l.lesson)}</p><p><strong>${esc(l.front)}</strong><br>${esc(l.answer)}</p><p class="muted">Some reference commands are beyond the current access-lab simulator’s supported command set.</p></details>`).join('');}
function traffic(){const m=profile.activeMission;if(m.mode==='assessment')return;showModal('Follow a customer packet',`<p>Destination: <code>198.51.100.10</code></p><ol class="traffic-path">${pathState(m).map(s=>`<li class="${s.passes?'good':s.reached?'bad':'muted'}">${icon(s.passes?'check':s.reached?'close':'pause')}<div><strong>${s.name}</strong><p>${s.passes?'Forwarding succeeds.':s.reached?esc(s.reason):'Not reached by this packet.'}</p></div></li>`).join('')}</ol><details><summary>Packet and forwarding context</summary><p>Source ${m.client.ip} → destination 198.51.100.10. Ethernet next hops change at routed boundaries; the customer access service requires VLAN ${m.vlan}. This teaching model evaluates the service path rather than emulating every packet header.</p></details>`);}
function openSettings(){const s=profile.settings;showModal('Workspace settings',`<form id="settings-form"><label class="check-label"><input type="checkbox" name="skipIntro" ${s.skipIntro?'checked':''}> Skip the terminal opening after onboarding</label><label>Accent color<select name="theme"><option value="cyan" ${s.theme==='cyan'?'selected':''}>Operations cyan</option><option value="blue" ${s.theme==='blue'?'selected':''}>Cool blue</option><option value="violet" ${s.theme==='violet'?'selected':''}>Night violet</option></select></label><label>Text size<select name="textSize"><option value="normal" ${s.textSize==='normal'?'selected':''}>Standard</option><option value="large" ${s.textSize==='large'?'selected':''}>Larger</option></select></label><label class="check-label"><input type="checkbox" name="comfortable" ${s.comfortable?'checked':''}> Comfortable spacing</label><button class="button primary" type="submit">Save settings</button></form><hr><h3>Offline installation</h3><p>${'serviceWorker' in navigator?'Install from your browser’s menu after this page finishes downloading. On iPhone or iPad, use Share → Add to Home Screen.':'Service workers are unavailable in this browser.'}</p><p id="offline-state" class="muted">${navigator.serviceWorker?.controller?'The offline app is installed in this browser.':'Offline installation is pending. Use the built app over HTTPS or localhost.'}</p>${button('Check storage','storage','secondary')}${button('Export local progress','export','secondary')}<label class="file-label">Import a local progress export<input type="file" id="import-file" accept="application/json,.json"></label><p class="build-note">Local exports are unencrypted progress snapshots. Account-bound encrypted full backups are not implemented in this development build.</p>`);}
function downloadFile(name,contents,type='application/json'){const url=URL.createObjectURL(new Blob([contents],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

document.addEventListener('click',async e=>{
  if(ui.phase==='intro'&&e.target.closest('.boot-screen'))document.querySelector('#boot-input')?.focus({preventScroll:true});
  const b=e.target.closest('[data-action]');if(!b)return;if(b.disabled)return;e.preventDefault();const action=b.dataset.action,id=b.dataset.id,s=profile?.session,m=profile?.activeMission;
  try{
    if(action==='close-modal'){closeModal();return;}
    if(action==='menu'){ui.menu=!ui.menu;render();return;}
    if(action==='begin-gate'){beginGate();return;}
    if(action==='gate-answer'){gate.items[gate.index].response=Number(b.dataset.index);save();render();return;}
    if(action==='gate-prev'){gate.index=Math.max(0,gate.index-1);save();render();return;}
    if(action==='gate-next'){if(gate.index===9)await finishGate();else{gate.index++;save();render();}return;}
    if(action==='gate-inspect'){toast(inspect(gate.items[gate.index].network,'ont'));save();return;}
    if(action==='gate-power'){setPhysical(gate.items[gate.index].network,'power',true);save();render();return;}
    if(action==='pause-gate'){pauseClock(gate.clock);save();render();return;}
    if(action==='resume-gate'){resumeClock(gate.clock);if(gate.clock.ended)await finishGate(true);else{save();render();}return;}
    if(action==='plan'){showModal('How much time do you have?',`<p>Choose a session length and your focus.</p><form id="plan-form"><label>Time available<select name="minutes">${[10,15,20,25,30,45,60].map(n=>`<option ${n===(profile.plan?.minutes??20)?'selected':''}>${n}</option>`).join('')}</select></label><label>Focus<select name="goal"><option value="ccna" ${profile.goal==='ccna'?'selected':''}>CCNA preparation</option><option value="career" ${profile.goal==='career'?'selected':''}>Practical job skills</option></select></label><button class="button primary" type="submit">Build today’s plan</button></form>`);return;}
    if(action==='domain'){ui.domain=id;ui.query='';go('study');return;}
    if(action==='go-study'){go('study');return;}
    if(action==='go-career'){go('career');return;}
    if(action==='lesson'){ui.lesson=id;profile.activity.push({type:'lesson',skill:id,domain:lessonById(id).domain,at:Date.now()});save();go('lesson');return;}
    if(action==='bookmark'){profile.bookmarks=profile.bookmarks.includes(id)?profile.bookmarks.filter(x=>x!==id):[...profile.bookmarks,id];save();render();return;}
    if(action==='study-mode'||action==='study-setup'){setupStudy(b.dataset.mode??ui.studyMode);return;}
    if(action==='skill-practice'){setupStudy('questions',id);return;}
    if(action==='answer'){const q=s.items[s.index];q.response=Number(b.dataset.index);if(s.feedback==='end')q.checked=false;save();render();return;}
    if(action==='flag'){s.items[s.index].flag=!s.items[s.index].flag;save();render();return;}
    if(action==='flip'){ui.flipped=!ui.flipped;render();return;}
    if(action==='typed-flash'){ui.typedFlash=true;render();return;}
    if(action==='self-check'){s.items[s.index].response=b.dataset.value==='true';checkItem(s.items[s.index],'flashcards');await nextQuestion();return;}
    if(action==='pick-word'){const q=s.items[s.index];q.pieces.push(Number(id));q.response=q.pieces.map(i=>q.bank.find(b=>b.id===i).text).join(' ');save();render();return;}
    if(action==='unpick-word'){const q=s.items[s.index];if(q.checked)return;q.pieces=q.pieces.filter(x=>x!==Number(id));q.response=q.pieces.map(i=>q.bank.find(b=>b.id===i).text).join(' ');save();render();return;}
    if(action==='check-answer'){checkCurrent();return;}
    if(action==='question-prev'||action==='question-jump'){s.index=action==='question-prev'?Math.max(0,s.index-1):Number(b.dataset.index);ui.flipped=false;markExposure(s.items[s.index]);save();render();return;}
    if(action==='question-next'){await nextQuestion();return;}
    if(action==='finish-study'){await completeStudy();return;}
    if(action==='pause-study'){pauseClock(s.clock);save();render();return;}
    if(action==='resume-study'){resumeClock(s.clock);if(s.clock.ended)await completeStudy('interrupted');else{save();render();}return;}
    if(action==='first-mission'){startMission(1,'guided');return;}
    if(action==='new-sandbox'){startMission(1,'guided',freshSeed(),true);return;}
    if(action==='mission-setup'){missionSetup(Number(b.dataset.difficulty));return;}
    if(action==='start-mission'){startMission(Number(b.dataset.difficulty),b.dataset.mode);return;}
    if(action==='replace-mission'){profile.history.push({id:crypto.randomUUID(),type:'recovery-copy',at:Date.now(),mission:structuredClone(m)});ui.replaceApproved=true;startMission(Number(b.dataset.difficulty),b.dataset.mode,b.dataset.seed,b.dataset.sandbox==='true');return;}
    if(action==='resume-mission'){go('mission');return;}
    if(action==='mission-tab'){syncDocs();ui.missionTab=id;save();render();return;}
    if(action==='device'){m.activeDevice=id;ui.missionTab='terminal';ui.commandDraft='';ui.assistedDraft=false;closeModal();save();render();return;}
    if(action==='builder'){ui.builder=!ui.builder;render();return;}
    if(action==='insert-command'){ui.commandDraft=document.querySelector('#builder-command').value;ui.assistedDraft=true;render();document.querySelector('#command-input')?.focus();return;}
    if(action==='equipment'){equipment(id);return;}
    if(action==='inspect'){const result=inspect(m,id);save();showModal(id==='order'?'Service order':'Inspection',`<pre>${esc(result)}</pre>`);return;}
    if(action==='physical'){setPhysical(m,b.dataset.key,b.dataset.value==='true');save();equipment('ont');return;}
    if(action==='cable'){cableStep();return;}
    if(action==='cable-step'){cableStep(Number(b.dataset.step));return;}
    if(action==='connect-cable'){setPhysical(m,'cable',true);save();equipment('ont');toast('Ethernet connected: ONT GE1 → router WAN.');return;}
    if(action==='test'){if(m.mode==='assessment'&&id!=='confirm'){toast('Use the workstation terminal to perform assessment tests.');return;}const result=runTest(m,id);save();showModal(id==='confirm'?'Customer confirmation':'Test result',`<pre>${esc(result.detail)}</pre>`);return;}
    if(action==='hint'){if(m.mode==='assessment')return;showModal('Mara · Field mentor',`<div class="mentor-note">${icon('bulb')}<p>${esc(getHint(m))}</p></div>`);save();return;}
    if(action==='reference'){reference();return;}
    if(action==='traffic'){traffic();return;}
    if(action==='conversation'){conversation();return;}
    if(action==='ask-customer'){answerCustomer(['When did this start?','Is every device affected?','Has anything changed?','What do the equipment lights show?'][Number(b.dataset.index)]);return;}
    if(action==='save-ticket'){syncDocs();await save();toast('Ticket notes saved.');return;}
    if(action==='complete-mission'){await completeMission();return;}
    if(action==='leave-mission'){showModal('Leave this assignment?',`<p>Your configuration, findings, and notes are saved.</p>${button('Pause assignment','pause-mission','primary')}${m.mode!=='assessment'?button('Leave it running','run-mission','secondary'):''}${button('Keep working','close-modal','text')}`);return;}
    if(action==='pause-mission'){syncDocs();if(m.clock)pauseClock(m.clock);m.paused=true;save();closeModal();go('career');return;}
    if(action==='run-mission'){syncDocs();m.paused=false;save();closeModal();go('career');return;}
    if(action==='resume-practical'){resumeClock(m.clock);m.paused=false;if(m.clock.ended){m.failed=true;m.status='failed';m.failReason='The interruption allowance ended. Start a fresh practical attempt.';}save();render();return;}
    if(action==='recover'){m.mode='guided';m.clock=null;m.status='active';m.recovery=true;save();render();return;}
    if(action==='failed-debrief'){m.status='complete';save();render();return;}
    if(action==='replay'){startMission(m.difficulty,m.mode,m.seed);return;}
    if(action==='variation'){startMission(m.difficulty,m.mode);return;}
    if(action==='copy-seed'){await navigator.clipboard.writeText(shareSeed(m));toast('Seed copied.');return;}
    if(action==='seed'){showModal('Open a shared challenge',`<form id="seed-form"><label>Seed or share code<input name="seed" maxlength="200" placeholder="FIELD:access-1.0.0:1:…" required autocomplete="off" autocorrect="off" autocapitalize="none"></label><p class="muted">Opens a separate challenge network. The same seed and generator version reproduce the same environment.</p><button class="button primary" type="submit">Open challenge</button></form>`);return;}
    if(action==='compatible-seed'){startMission(Number(b.dataset.difficulty),'guided',b.dataset.seed);return;}
    if(action==='escalate'){showModal('Request an authorized change',`<p>Mara can carry out a correctly specified change on Edge-R1. Include the device, the exact command, the reason, and your verification plan.</p><form id="escalation-form"><label>Device<select name="device"><option value="edge">Edge-R1</option></select></label><label>Configuration command<input name="command" placeholder="Command to apply" autocomplete="off" required></label><label>Reason and verification<textarea name="reason" required placeholder="What evidence supports this change? How will you verify it?"></textarea></label><button class="button primary" type="submit">Send request to Mara</button></form>`);return;}
    if(action==='settings'){openSettings();return;}
    if(action==='storage'){const estimate=await navigator.storage?.estimate();const persistent=await navigator.storage?.persist?.();showModal('On-device storage',`<p>${estimate?`${(estimate.usage/1048576).toFixed(1)} MB used · ${(estimate.quota/1048576).toFixed(0)} MB browser quota`:'Storage estimation is unavailable.'}</p><p>${persistent?'Persistent storage was granted.':'The browser may clear site data under storage pressure. Keep a backup of important work.'}</p>`);return;}
    if(action==='export'){syncDocs();await save();downloadFile('the-field-progress.json',JSON.stringify(profile,null,2));return;}
    if(action==='confirm-import'){profile=ui.imported;ui.imported=null;await save();closeModal();ui.phase=profile.gate==='passed'?'ready':profile.gate==='locked'?'locked':'gate';gate=profile.gateAttempt??null;go('profile');toast('Local progress restored.');return;}
    if(action==='avatar'){showModal('Your technician',`<p>Choose your workwear accent.</p><div class="avatar-options">${['blue','cyan','orange','violet'].map(c=>`<button class="avatar ${c}" data-action="avatar-color" data-id="${c}" aria-label="${c} workwear">${icon('user')}</button>`).join('')}</div>`);return;}
    if(action==='avatar-color'){profile.career.avatar.color=id;save();closeModal();render();return;}
    if(action==='note'){showModal('Add a personal note',`<form id="note-form"><input type="hidden" name="topic" value="${esc(id)}"><label>${esc(lessonById(id)?.title??id)}<textarea name="text" rows="5" required maxlength="5000"></textarea></label><button class="button primary" type="submit">Save note</button></form>`);return;}
    if(['new-card','make-card','edit-card'].includes(action)){const c=action==='edit-card'?profile.cards.find(c=>c.id===id):action==='make-card'?{front:lessonById(id).front,back:lessonById(id).answer,source:id}:{front:'',back:''};showModal('Personal flashcard',`<form id="card-form"><input type="hidden" name="id" value="${esc(c.id??'')}"><input type="hidden" name="source" value="${esc(c.source??'')}"><label>Front<textarea name="front" required>${esc(c.front)}</textarea></label><label>Back<textarea name="back" required>${esc(c.back)}</textarea></label><button class="button primary" type="submit">Save card</button></form>`);return;}
    if(action==='update'){syncDocs();await save();registration?.waiting?.postMessage('ACTIVATE_UPDATE');return;}
  }catch(error){toast(error.message);}
});

function checkCurrent(){const s=profile.session,q=s.items[s.index];if(s.mode==='blank'||(s.mode==='flashcards'&&ui.typedFlash))q.response=document.querySelector('#answer-text')?.value??q.response;if(q.response===null||q.response===''){toast('Enter an answer first.');return;}if(s.feedback==='end'){save();nextQuestion();return;}checkItem(q,s.mode);markExposure(q);save();render();}
async function nextQuestion(){const s=profile.session;const text=document.querySelector('#answer-text');if(text)s.items[s.index].response=text.value;if(s.index===s.items.length-1){await completeStudy();return;}s.index++;ui.flipped=false;markExposure(s.items[s.index]);save();render();}
async function completeMission(){const m=profile.activeMission;if(m.status==='complete')return;syncDocs();const check=assessmentChecklist(m);if(!check.every(c=>c.ok)){showModal('Before closing the ticket',`<p>${m.mode==='assessment'?'The required job outcomes have not all been met. Review the stated requirements and your evidence.':'A few required outcomes still need attention.'}</p>${m.mode==='assessment'?'':check.filter(c=>!c.ok).map(c=>`<div class="check-row">${icon('clock')}<span>${esc(c.label)}</span></div>`).join('')}`);save();return;}
  const key=challengeKey(m),repeats=profile.repeats[key]??0,base=100+m.difficulty*50;
  m.credit=careerCredit({base:m.sandbox||m.recovery?0:base,repeats,guided:m.mode==='guided',...m.help});m.status='complete';m.completedAt=Date.now();if(m.clock)m.clock.ended=true;
  if(!m.sandbox&&!m.recovery){profile.repeats[key]=repeats+1;profile.xp+=m.credit.total;}
  profile.history.push({id:crypto.randomUUID(),type:'mission',at:Date.now(),passed:true,seed:m.seed,version:m.version,mode:m.mode,credit:m.credit.total,mission:structuredClone(m)});profile.activity.push({type:'mission',at:Date.now(),skill:m.faults.map(f=>FAULTS[f].skill).join(',')});await save();closeModal();render();}

document.addEventListener('submit',async e=>{
  e.preventDefault();const form=e.target,data=new FormData(form);try{
    if(form.id==='boot-form'){
      const value=document.querySelector('#boot-input').value.trim();if(ui.codeMode){await redeemAuthorization(value,profile,deployment.prerequisiteIssuer);await save();ui.codeMode=false;ui.bootText='';ui.bootError='';await enterApp();}
      else if(value.toLowerCase()==='enable'){if(profile?.gate==='locked'){ui.codeMode=true;ui.bootText='';ui.bootError='';intro();}else await enterApp();}
      else{ui.bootError='% command not recognized';ui.bootText='';intro();}return;
    }
    if(form.id==='onboard-form'){profile=newProfile(data.get('name').trim(),data.get('goal'));if(!profile.name)return;await save();ui.phase='gate';render();return;}
    if(form.id==='gate-command'){const item=gate.items[gate.index],t=PREREQUISITE_TASKS.find(t=>t.id===item.task);execute(item.network,t.device,data.get('command'));await save();render();document.querySelector('#gate-input')?.focus();return;}
    if(form.id==='plan-form'){profile.plan={minutes:Number(data.get('minutes')),at:Date.now()};profile.goal=data.get('goal');save();closeModal();render();return;}
    if(form.id==='study-setup-form'){const assessment=data.has('assessment');const settings={mode:assessment?'questions':data.get('mode'),domain:data.get('domain'),skill:data.get('skill')||null,count:Number(data.get('count')),feedback:data.get('feedback'),seed:freshSeed(),assessment};
      // Validate before ending a current session. Preserve the ended session for later review.
      newStudy({...settings,exposures:profile.exposures});if(profile.session?.status==='active')await completeStudy('restarted');
      profile.session=newStudy({...settings,exposures:profile.exposures});markExposure(profile.session.items[0]);ui.flipped=false;save();closeModal();go('session');return;}
    if(form.id==='typed-answer'){checkCurrent();return;}
    if(form.id==='command-form'){const m=profile.activeMission;if(m.failed&&m.status==='failed'){toast('Choose recovery practice before continuing.');return;}const raw=data.get('command');execute(m,m.activeDevice,raw,{assisted:ui.assistedDraft,authorized:!(m.mode==='career'&&m.activeDevice==='edge')});ui.commandDraft='';ui.assistedDraft=false;await save();render();document.querySelector('#command-input')?.focus({preventScroll:true});return;}
    if(form.id==='client-settings'){setClient(profile.activeMission,Object.fromEntries(data));await save();closeModal();render();toast('Workstation settings applied. Verify the result.');return;}
    if(form.id==='customer-question'){answerCustomer(data.get('question'));return;}
    if(form.id==='seed-form'){const parsed=parseSeed(data.get('seed'));if(parsed.version!==GENERATOR_VERSION){showModal('Generator version differs',`<p>This installation has ${GENERATOR_VERSION}; the seed requests ${esc(parsed.version)}. A matching-version download is not available in this build. You can create a clearly different compatible variation.</p>${button('Create compatible variation','compatible-seed','primary',`data-seed="${esc(parsed.seed+'-compatible')}" data-difficulty="${parsed.difficulty}"`)}`);return;}startMission(parsed.difficulty,'career',parsed.seed);return;}
    if(form.id==='escalation-form'){const m=profile.activeMission,command=data.get('command').trim(),reason=data.get('reason').trim();
      if(!/^ip route 0\.0\.0\.0 0\.0\.0\.0 (?:\d{1,3}\.){3}\d{1,3}$/.test(command)||reason.split(/\s+/).length<8){m.help.clues++;save();showModal('Mara · Request needs detail','<p>Tell me the exact default-route command, what the routing evidence shows, and how you’ll verify reachability after I apply it.</p>'+button('Revise request','escalate','primary'));return;}
      const count=m.help.submitted,built=m.help.built;for(const c of ['enable','configure terminal',command,'end','copy running-config startup-config'])execute(m,'edge',c);m.help.submitted=count;m.help.built=built;evidence(m,'Authorized coworker change',command+'\n'+reason);save();showModal('Mara · Change applied','<p>I applied and saved your requested configuration. Please verify the customer service and document the outcome.</p>');return;}
    if(form.id==='settings-form'){Object.assign(profile.settings,{skipIntro:data.has('skipIntro'),theme:data.get('theme'),textSize:data.get('textSize'),comfortable:data.has('comfortable')});await save();closeModal();render();return;}
    if(form.id==='note-form'){profile.notes.push({id:crypto.randomUUID(),topic:data.get('topic'),text:data.get('text'),updatedAt:Date.now()});save();closeModal();toast('Personal note saved.');return;}
    if(form.id==='card-form'){const id=data.get('id')||crypto.randomUUID(),existing=profile.cards.findIndex(c=>c.id===id),card={id,front:data.get('front'),back:data.get('back'),source:data.get('source'),edited:true,updatedAt:Date.now()};if(existing>=0)profile.cards[existing]=card;else profile.cards.push(card);save();closeModal();render();toast('Card saved to your personal deck.');return;}
  }catch(error){if(form.id==='boot-form'){ui.bootError=error.message;ui.bootText='';intro();}else toast(error.message);}
});
document.addEventListener('input',e=>{
  if(e.target.id==='boot-input'){ui.bootText=e.target.value;document.querySelector('#boot-display').textContent=ui.bootText;}
  if(e.target.id==='command-input')ui.commandDraft=e.target.value;
  if(e.target.id==='reference-search')document.querySelector('#reference-results').innerHTML=referenceItems(e.target.value);
  if(e.target.id==='study-search'){const caret=e.target.selectionStart;ui.query=e.target.value;render();const input=document.querySelector('#study-search');input.focus();input.setSelectionRange(caret,caret);}
  if(e.target.closest('#ticket-docs')){syncDocs();save();}
  if(e.target.id==='answer-text'&&profile.session){profile.session.items[profile.session.index].response=e.target.value;save();}
});
document.addEventListener('change',async e=>{try{
  if(e.target.id==='device-select'){profile.activeMission.activeDevice=e.target.value;ui.commandDraft='';ui.assistedDraft=false;save();render();}
  if(e.target.dataset.evidence){const id=e.target.dataset.evidence,docs=profile.activeMission.docs;docs.evidence=e.target.checked?[...new Set([...docs.evidence,id])]:docs.evidence.filter(x=>x!==id);save();}
  if(e.target.id==='import-file'){const file=e.target.files[0];if(!file)return;if(file.size>10*1048576)throw new Error('Progress imports are limited to 10 MB.');const data=validateBackup(JSON.parse(await file.text()));ui.imported=data;showModal('Preview local restore',`<p>Profile: <strong>${esc(data.name)}</strong><br>History records: ${data.history.length}<br>Experience: ${data.xp} XP</p><p>This replaces local progress. Export your current work first if you need to preserve it.</p>${button('Export current progress','export','secondary')}${button('Replace local progress','confirm-import','primary')}`);}
}catch(error){toast(error.message);}});
window.addEventListener('hashchange',()=>{if(ui.phase!=='ready')return;const next=location.hash.slice(1)||'today';if(ui.route==='mission'&&next!=='mission'){syncDocs();if(profile.activeMission?.clock&&!profile.activeMission.clock.ended)pauseClock(profile.activeMission.clock);save();}if(ui.route==='session'&&next!=='session'&&profile.session?.clock&&!profile.session.clock.ended){pauseClock(profile.session.clock);save();}ui.route=next;ui.menu=false;render();window.scrollTo({top:0});});
document.addEventListener('visibilitychange',()=>{if(!profile)return;if(document.hidden){syncDocs();for(const clock of [gate?.clock,profile.session?.status==='active'?profile.session.clock:null,profile.activeMission?.status==='active'?profile.activeMission.clock:null])if(clock)pauseClock(clock);save();}else{render();}});
window.addEventListener('pagehide',()=>{syncDocs();for(const clock of [gate?.clock,profile.session?.status==='active'?profile.session.clock:null,profile.activeMission?.status==='active'?profile.activeMission.clock:null])if(clock)pauseClock(clock);save();});
window.addEventListener('online',()=>{if(ui.phase==='ready')render();});window.addEventListener('offline',()=>{if(ui.phase==='ready')render();});
setInterval(()=>{if(!profile)return;const clock=ui.phase==='gate'?gate?.clock:ui.route==='session'&&profile.session?.status==='active'?profile.session.clock:ui.route==='mission'&&profile.activeMission?.status==='active'?profile.activeMission.clock:null;if(!clock||clock.ended)return;tick(clock);const el=document.querySelector('#clock');if(el)el.textContent=formatTime(clock.remaining);if(clock.ended){if(ui.phase==='gate')finishGate(clock.reason==='interrupted');else if(ui.route==='session')completeStudy(clock.reason);else{profile.activeMission.failed=true;profile.activeMission.status='failed';profile.activeMission.failReason=clock.reason==='interrupted'?'The interruption allowance ended. Start a fresh practical attempt.':'The assessment timer expired.';save();render();}}},500);

async function bootstrap(){
  try{
    if(navigator.locks){const acquired=await new Promise(resolve=>{navigator.locks.request('the-field-writer',{ifAvailable:true},async lock=>{if(!lock){resolve(false);return;}resolve(true);await new Promise(r=>lockResolve=r);});});if(!acquired){root.innerHTML='<div class="pause-screen"><h1>Workspace open in another tab.</h1><p>Close the other tab, then reload here to protect your local work.</p></div>';return;}}
    await openStore();profile=await readState();deployment=await fetch('./deployment.json').then(r=>r.json()).catch(()=>({}));gate=profile?.gateAttempt??null;
    // A suspended or closed process does not consume unlimited assessment time on reload.
    for(const clock of [gate?.clock,profile?.session?.status==='active'?profile.session.clock:null,profile?.activeMission?.status==='active'?profile.activeMission.clock:null])if(clock&&clock.pausedAt===null&&!clock.ended){clock.pausedAt=clock.last;}
    ready=true;if(profile?.settings.skipIntro&&profile.gate==='passed')await enterApp();else render();
    if('serviceWorker' in navigator){registration=await navigator.serviceWorker.register('./sw.js').catch(()=>null);if(registration){ui.updateReady=!!registration.waiting;registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller){ui.updateReady=true;if(ui.phase==='ready')render();}});});let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(ui.updateReady&&!reloading){reloading=true;location.reload();}});}}
  }catch(error){root.innerHTML=`<div class="pause-screen"><h1>The workspace could not open.</h1><p>${esc(error.message)}</p><p>Allow website storage and reload. Your existing data has not been reset.</p></div>`;}
}
bootstrap();
